# Generated by Django 2.1.2 on 2018-12-01 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainPage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productionSpeed', models.IntegerField(default=1)),
                ('pointsPerLvl', models.IntegerField(default=5)),
                ('food', models.IntegerField(default=10)),
                ('electrity', models.IntegerField(default=10)),
                ('ore', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='CityOwned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default='City', max_length=100)),
                ('is_capital', models.BooleanField(default=False)),
                ('pos_x', models.IntegerField(default=1)),
                ('pos_y', models.IntegerField(default=1)),
                ('town_hall', models.IntegerField(default=1)),
                ('barracks', models.IntegerField(default=1)),
                ('roads', models.IntegerField(default=1)),
                ('mines', models.IntegerField(default=1)),
                ('power_plant', models.IntegerField(default=1)),
                ('farms', models.IntegerField(default=1)),
                ('housing', models.IntegerField(default=1)),
                ('infantry', models.IntegerField(default=0)),
                ('hinfantry', models.IntegerField(default=0)),
                ('planes', models.IntegerField(default=0)),
                ('ltanks', models.IntegerField(default=0)),
                ('htanks', models.IntegerField(default=0)),
                ('motorized', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
                ('electricity', models.IntegerField(default=0)),
                ('ore', models.IntegerField(default=0)),
                ('population', models.IntegerField(default=100)),
                ('points', models.IntegerField(default=100)),
                ('city_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainPage.Server')),
            ],
        ),
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceProduction', models.IntegerField(default=10)),
                ('pointsPerLvl', models.IntegerField(default=2)),
                ('food', models.IntegerField(default=10)),
                ('electrity', models.IntegerField(default=10)),
                ('ore', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='HInfantry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=30)),
                ('attack', models.IntegerField(default=30)),
                ('speed', models.IntegerField(default=10)),
                ('capacity', models.IntegerField(default=10)),
                ('food', models.IntegerField(default=10)),
                ('electrity', models.IntegerField(default=10)),
                ('ore', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField(default=100)),
                ('pointsPerLvl', models.IntegerField(default=1)),
                ('food', models.IntegerField(default=10)),
                ('electrity', models.IntegerField(default=10)),
                ('ore', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='HTanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=200)),
                ('attack', models.IntegerField(default=100)),
                ('speed', models.IntegerField(default=30)),
                ('capacity', models.IntegerField(default=150)),
                ('food', models.IntegerField(default=10)),
                ('electrity', models.IntegerField(default=10)),
                ('ore', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Infantry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=10)),
                ('attack', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=20)),
                ('capacity', models.IntegerField(default=30)),
                ('food', models.IntegerField(default=10)),
                ('electrity', models.IntegerField(default=10)),
                ('ore', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='LTanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=100)),
                ('attack', models.IntegerField(default=100)),
                ('speed', models.IntegerField(default=80)),
                ('capacity', models.IntegerField(default=100)),
                ('food', models.IntegerField(default=10)),
                ('electrity', models.IntegerField(default=10)),
                ('ore', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceProduction', models.IntegerField(default=10)),
                ('pointsPerLvl', models.IntegerField(default=2)),
                ('food', models.IntegerField(default=10)),
                ('electrity', models.IntegerField(default=10)),
                ('ore', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Motorized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=50)),
                ('attack', models.IntegerField(default=50)),
                ('speed', models.IntegerField(default=100)),
                ('capacity', models.IntegerField(default=250)),
                ('food', models.IntegerField(default=10)),
                ('electrity', models.IntegerField(default=10)),
                ('ore', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=100)),
                ('attack', models.IntegerField(default=200)),
                ('speed', models.IntegerField(default=300)),
                ('capacity', models.IntegerField(default=150)),
                ('food', models.IntegerField(default=10)),
                ('electricity', models.IntegerField(default=10)),
                ('ore', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceProduction', models.IntegerField(default=10)),
                ('pointsPerLvl', models.IntegerField(default=2)),
                ('food', models.IntegerField(default=10)),
                ('electrity', models.IntegerField(default=10)),
                ('ore', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productionSpeed', models.IntegerField(default=1)),
                ('pointsPerLvl', models.IntegerField(default=3)),
                ('food', models.IntegerField(default=10)),
                ('electrity', models.IntegerField(default=10)),
                ('ore', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='TownHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productionSpeed', models.IntegerField(default=1)),
                ('lvlToUnlockPlanes', models.IntegerField(default=25)),
                ('lvlToUnlockHtanks', models.IntegerField(default=20)),
                ('lvlToUnlockLtanks', models.IntegerField(default=15)),
                ('lvlToUnlockMotorized', models.IntegerField(default=10)),
                ('lvlToUnlockHinfantry', models.IntegerField(default=5)),
                ('pointsPerLvl', models.IntegerField(default=10)),
                ('food', models.IntegerField(default=10)),
                ('electrity', models.IntegerField(default=10)),
                ('ore', models.IntegerField(default=10)),
            ],
        ),
    ]
