# Generated by Django 2.1.2 on 2018-12-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityMap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityowned',
            name='research_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='research_f',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='research_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='research_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='research_pp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='research_r',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='research_th1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='research_th2',
            field=models.IntegerField(default=0),
        ),
    ]
