"""
Django settings for projektNaChmureDJango project.

Generated by 'django-admin startproject' using Django 2.1.2.

"""

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = '%hvda=l7_z0&lw%gljyv6_5m59p7y3#bqb!jz=@k%df_704w8_'

DEBUG = True

ALLOWED_HOSTS = ['solwit-pjatk-arc-2018-gr1.appspot.com', '127.0.0.1', '404', '500']
handler500 = 'mainPage.views.page_not_found_view'
handler404 = 'mainPage.views.page_not_found_view'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'paypal.standard.ipn',
    'social_django',
    'alliance',
    'cityMap',
    'kontakt',
    'mainPage',
    'messagess',
    'premium',
    'profileUser',
    'rankings',
    'raports',
    'scheduleTasks',
    'worldMap',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'projektNaChmureDJango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'projektNaChmureDJango.wsgi.application'

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

import pymysql  # noqa: 402

pymysql.install_as_MySQLdb()
if os.getenv('GAE_APPLICATION', None):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': '/cloudsql/solwit-pjatk-arc-2018-gr1:europe-west1:test1',
            'USER': 'root',
            'PASSWORD': 'root',
            'NAME': 'ccpx1',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)

# pliki statyczne beda przechowywane wspolnie w tym folderze
STATIC_URL = '/static/'
STATIC_ROOT = 'static'

#  domyslnie pobieraj z storage
MEDIA_ROOT = 'https://console.cloud.google.com/storage/solwit-pjatk-arc-2018-gr1.appspot.com'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# domyslnie wysylaj do google storage
DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
GS_BUCKET_NAME = 'solwit-pjatk-arc-2018-gr1.appspot.com'

# rest podstawowa konfiguracja
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

# email do rejestracji
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'kontonazajecia123@gmail.com'
EMAIL_HOST_PASSWORD = 'zsadsadaA1'
EMAIL_PORT = 587

# paypal
PAYPAL_RECEIVER_EMAIL = 'parzyjaglakamil@gmail.com'
PAYPAL_IDENTITY_TOKEN = 'KrMpKsJG09azuxURUTJhvXG2HKgGSJV_DNYeVYxhdIlrgSlTwOFpUXlo2re'
PAYPAL_TEST = True

# facebook
SOCIAL_AUTH_FACEBOOK_KEY = '2261094383941531'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = '50767d778053d85f5cf80574a2f3a8dd'  # App Secret

# github
SOCIAL_AUTH_GITHUB_KEY = '9a49fd4678459ffb3de7'  # App ID
SOCIAL_AUTH_GITHUB_SECRET = 'd04594c8a218e393b0ba0bc15c44e28b58660535'  # App Secret

# po poprawnym zalogowaniu przenieś na stronę główną
LOGIN_URL = '/'
LOGOUT_URL = '/'
LOGIN_REDIRECT_URL = '/'
